<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
     name="RECEPCION_DEVOLUCION" 
     targetNamespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_DEVOLUCION" 
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
     xmlns:tns="http://soap.sctinst.redsys.es/consumed/RECEPCION_DEVOLUCION"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="RecepcionDevolucionPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>    
    <xsd:schema>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_DEVOLUCION" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_DEVOLUCION_Request.xsd">
    	</xsd:import>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_DEVOLUCION" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_DEVOLUCION_Response.xsd">
    	</xsd:import>
    </xsd:schema>
  </wsdl:types>
    
  <wsdl:message name="recepcionDevolucionOpRequest">
    <wsdl:part name="WS_RECEPCION_Devolucion_Request" element="tns:Input"/>
  </wsdl:message>
  <wsdl:message name="recepcionDevolucionOpResponse">
    <wsdl:part  name="WS_RECEPCION_Devolucion_Response" element="tns:Output"/>
  </wsdl:message>
  
  <wsdl:portType name="iSCTRefund">
    <wsdl:operation name="recepcionDevolucionOp">
      <wsdl:input message="tns:recepcionDevolucionOpRequest"/>
      <wsdl:output message="tns:recepcionDevolucionOpResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="RecepcionDevolucionPortBinding" type="tns:iSCTRefund">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="recepcionDevolucionOp">
      <soap:operation soapAction="http://soap.sctinst.redsys.es/Consumed_Recepcion_Devolucion/recepcionDevolucionOp"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="WS_RECEPCION_DEVOLUCION">
    <wsdl:port binding="tns:RecepcionDevolucionPortBinding" name="iSCTRefundPort">
      <soap:address location="http://localhost:7800/WS_RECEPCION_DEVOLUCION"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>