<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
     name="ENVIO_DEVOLUCION" 
     targetNamespace="http://soap.sctinst.redsys.es/exposed/ENVIO_DEVOLUCION" 
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
     xmlns:tns="http://soap.sctinst.redsys.es/exposed/ENVIO_DEVOLUCION" 
     xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <!-- <generatedXSD location="Exposed_WS_Envio_Devolucion_InlineSchema1.xsd"/> -->
        <binding hasEncoding="false" imported="true" name="EnvioDevolucionPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
      <xsd:schema>
		<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/ENVIO_DEVOLUCION" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_ENVIO_DEVOLUCION_Request.xsd">
    	</xsd:import>
		<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/ENVIO_DEVOLUCION" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_ENVIO_DEVOLUCION_Response.xsd">
    	</xsd:import>
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="envioDevolucionOpRequest">
    <wsdl:part element="tns:Input" name="WS_Envio_Devolucion_Request"/>
  </wsdl:message>
  <wsdl:message name="envioDevolucionOpResponse">
    <wsdl:part element="tns:Output" name="WS_Envio_Devolucion_Response"/>
  </wsdl:message>
  
  <wsdl:portType name="iSCTRefundOrder">
    <wsdl:operation name="envioDevolucionOp">
      <wsdl:input message="tns:envioDevolucionOpRequest"/>
      <wsdl:output message="tns:envioDevolucionOpResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="EnvioDevolucionPortBinding" type="tns:iSCTRefundOrder">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="envioDevolucionOp">
      <soap:operation soapAction="http://soap.sctinst.redsys.es/Exposed_Envio_Devolucion/envioDevolucionOp"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="WS_ENVIO_DEVOLUCION">
    <wsdl:port binding="tns:EnvioDevolucionPortBinding" name="iSCTRefundOrderPort">
      <soap:address location="https://sctinst-i.redsys.es/sbasico-entproc/WS_ENVIO_DEVOLUCION"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>