<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
     name="ENVIO_SOLICITUD" 
     targetNamespace="http://soap.sctinst.redsys.es/exposed/ENVIO_SOLICITUD" 
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
     xmlns:tns="http://soap.sctinst.redsys.es/exposed/ENVIO_SOLICITUD" 
     xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="EnvioSolicitudPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
 <wsdl:types>
     <xsd:schema>
		<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/ENVIO_SOLICITUD" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_ENVIO_SOLICITUD_Request.xsd">
    	</xsd:import>
		<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/ENVIO_SOLICITUD" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_ENVIO_SOLICITUD_Response.xsd">
    	</xsd:import>
    </xsd:schema>
 </wsdl:types>
 
  <wsdl:message name="envioSolicitudOpRequest">
  	<wsdl:part element="tns:Input" name="WS_Envio_Solicitud_Request"/>
  </wsdl:message>
  <wsdl:message name="envioSolicitudOpResponse">
  	<wsdl:part element="tns:Output" name="WS_Envio_Solicitud_Response"/>
  </wsdl:message>

  <wsdl:portType name="iSCTReversalRequest">
  	<wsdl:operation name="envioSolicitudOp">
  		<wsdl:input message="tns:envioSolicitudOpRequest"/>
  		<wsdl:output message="tns:envioSolicitudOpResponse"/>
  	</wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="EnvioSolicitudPortBinding" type="tns:iSCTReversalRequest">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="envioSolicitudOp">
      <soap:operation soapAction="http://soap.sctinst.redsys.es/Exposed_Envio_Solicitud/envioSolicitudOp"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="WS_ENVIO_SOLICITUD">
    <wsdl:port binding="tns:EnvioSolicitudPortBinding" name="iSCTRRPort">
      <soap:address location="https://sctinst-i.redsys.es/sbasico-entproc/WS_ENVIO_SOLICITUD"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>