<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    name="RECEPCION_CONF_ENVIO" 
    targetNamespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_CONF_ENVIO" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://soap.sctinst.redsys.es/consumed/RECEPCION_CONF_ENVIO" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="RecepcionConfEnvioPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_CONF_ENVIO" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_CONF_ENVIO_Request.xsd">
   		</xsd:import>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_CONF_ENVIO" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_CONF_ENVIO_Response.xsd">
   		</xsd:import>
	</xsd:schema>
  </wsdl:types>
    
  <wsdl:message name="recepcionConfEnvioOpRequest">
    <wsdl:part element="tns:Input" name="WS_RECEPCION_Conf_Envio_Request"/>
  </wsdl:message>
  <wsdl:message name="recepcionEnvioConfOpResponse">
    <wsdl:part element="tns:Output" name="WS_RECEPCION_Conf_Envio_Response"/>
  </wsdl:message>
  
  <wsdl:portType name="iSCTReceptionConfrm">
    <wsdl:operation name="recepcionConfEnvioOp">
      <wsdl:input message="tns:recepcionConfEnvioOpRequest"/>
      <wsdl:output message="tns:recepcionEnvioConfOpResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="RecepcionConfEnvioPortBinding" type="tns:iSCTReceptionConfrm">
  	<soap:binding style="document"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="recepcionConfEnvioOp">
  		<soap:operation
  			soapAction="http://soap.sctinst.redsys.es/Consumed_WS_Recepcion_Conf_Envio/recepcionConfEnvioOp" />
  		<wsdl:input>
  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="WS_RECEPCION_CONF_ENVIO">
    <wsdl:port binding="tns:RecepcionConfEnvioPortBinding" name="RecepcionConfEnvioPort">
      <soap:address location="http://localhost:7080/WS_RECEPCION_CONF_ENVIO"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>