<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
     name="RECEPCION_SOLICITUD" 
     targetNamespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_SOLICITUD" 
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
     xmlns:tns="http://soap.sctinst.redsys.es/consumed/RECEPCION_SOLICITUD" 
     xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">        
        <binding hasEncoding="false" imported="true" name="RecepcionSolicitudPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>    
      <xsd:schema>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_SOLICITUD" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_SOLICITUD_Request.xsd">
    	</xsd:import>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_SOLICITUD" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_SOLICITUD_Response.xsd">
    	</xsd:import>
    </xsd:schema>       
   </wsdl:types>
   
  <wsdl:message name="recepcionSolicitudOpRequest">
    <wsdl:part element="tns:Input" name="WS_Recepcion_Solicitud_Request"/>
  </wsdl:message>
  <wsdl:message name="recepcionSolicitudOpResponse">
    <wsdl:part element="tns:Output" name="WS_Recepcion_Solicitud_Response"/>
  </wsdl:message>
  
  <wsdl:portType name="iSCTRecpxnOfReversalReq">
    <wsdl:operation name="recepcionSolicitudOp">
      <wsdl:input message="tns:recepcionSolicitudOpRequest"/>
      <wsdl:output message="tns:recepcionSolicitudOpResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="RecepcionSolicitudPortBinding" type="tns:iSCTRecpxnOfReversalReq">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="recepcionSolicitudOp">
      <soap:operation soapAction="http://soap.sctinst.redsys.es/Consumed_Recepcion_Solicitud/recepcionSolicitudOp"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="WS_RECEPCION_SOLICITUD">
    <wsdl:port binding="tns:RecepcionSolicitudPortBinding" name="RecepcionSolicitudPort">
      <soap:address location="http://localhost:7080/WS_RECEPCION_SOLICITUD"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>