<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    name="RECEPCION_TRANSFERENCIA" 
    targetNamespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_TRANSFERENCIA" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://soap.sctinst.redsys.es/consumed/RECEPCION_TRANSFERENCIA" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="RecepcionTransferenciaPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
     <xsd:schema>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_TRANSFERENCIA" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_TRANSFERENCIA_Request.xsd">
    	</xsd:import>
		<xsd:import namespace="http://soap.sctinst.redsys.es/consumed/RECEPCION_TRANSFERENCIA" schemaLocation="../Redsys_Consumed_Lib/Consumed_WS_RECEPCION_TRANSFERENCIA_Response.xsd">
    	</xsd:import>
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="recepcionTransferenciaOpRequest">
    <wsdl:part element="tns:Input" name="WS_RECEPCION_Transferencia_Request"/>
  </wsdl:message>
  <wsdl:message name="recepcionTransferenciaOpResponse">
    <wsdl:part element="tns:Output" name="WS_RECEPCION_Transferencia_Response"/>
  </wsdl:message>
  
  <wsdl:portType name="iSCTRecpxnOfTransferReq">
    <wsdl:operation name="recepcionTransferenciaOp">
      <wsdl:input message="tns:recepcionTransferenciaOpRequest"/>
      <wsdl:output message="tns:recepcionTransferenciaOpResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="RecepcionTransferenciaPortBinding" type="tns:iSCTRecpxnOfTransferReq">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="recepcionTransferenciaOp">
      <soap:operation soapAction="http://soap.sctinst.redsys.es/Consumed_Recepcion_Transferencia/recepcionTransferenciaOp"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="WS_RECEPCION_TRANSFERENCIA">
    <wsdl:port binding="tns:RecepcionTransferenciaPortBinding" name="RecepcionTransferenciaPort">
      <soap:address location="http://localhost:7080/WS_RECEPCION_TRANSFERENCIA"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>