<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    name="CONSULTA_OPERACION" 
    targetNamespace="http://soap.sctinst.redsys.es/exposed/CONSULTA_OPERACION" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://soap.sctinst.redsys.es/exposed/CONSULTA_OPERACION" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="ConsultaOperacionPortBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
     <xsd:schema>
		<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/CONSULTA_OPERACION" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_CONSULTA_OPERACION_Request.xsd">
    	</xsd:import>
		<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/CONSULTA_OPERACION" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_CONSULTA_OPERACION_Response.xsd">
    	</xsd:import>
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="consultaOperacionOpRequest">
  	<wsdl:part element="tns:Input" name="WS_Consulta_Operacion_Request"/>
  </wsdl:message>
  <wsdl:message name="consultaOperacionOpResponse">
    <wsdl:part element="tns:Output" name="WS_Consulta_Operacion_Response"/>
  </wsdl:message>
  
  <wsdl:portType name="TxnOperationStatus">
    <wsdl:operation name="consultaOperacionOp">
      <wsdl:input message="tns:consultaOperacionOpRequest"/>
      <wsdl:output message="tns:consultaOperacionOpResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="ConsultaOperacionPortBinding" type="tns:TxnOperationStatus">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaOperacionOp">
      <soap:operation soapAction="http://soap.sctinst.redsys.es/Exposed_Consulta_Operacion/consultaOperacionOp"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="WS_CONSULTA_OPERACION">
    <wsdl:port binding="tns:ConsultaOperacionPortBinding" name="StatusConsultPort">
      <soap:address location="https://sctinst-i.redsys.es/sbasico-entadm/WS_CONSULTA_OPERACION"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>