<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	name="DISP_PLANIFICACION" 
	targetNamespace="http://soap.sctinst.redsys.es/exposed/DISP_PLANIFICACION"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:tns="http://soap.sctinst.redsys.es/exposed/DISP_PLANIFICACION"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<wsdl:documentation>
		<wsdl:appinfo source="WMQI_APPINFO">
			<MRWSDLAppInfo imported="true">
				<binding hasEncoding="false" imported="true"
					name="DispPlanificacionPortBinding" originalBindingStyle="document" />
			</MRWSDLAppInfo>
		</wsdl:appinfo>
	</wsdl:documentation>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/DISP_PLANIFICACION" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_DISP_PLANIFICACION_Request.xsd"></xsd:import>
			<xsd:import namespace="http://soap.sctinst.redsys.es/exposed/DISP_PLANIFICACION" schemaLocation="../Redsys_Exposed_Lib/Exposed_WS_DISP_PLANIFICACION_Response.xsd"></xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="dispPlanificacionRequest">
		<wsdl:part element="tns:Input" name="WS_DISP_PLANIFICACION_Request" />
	</wsdl:message>
	<wsdl:message name="dispPlanificacionResponse">
		<wsdl:part element="tns:Output" name="WS_DISP_PLANIFICACION_Response" />
	</wsdl:message>
	<wsdl:portType name="WsDispPlanificacion">
		<wsdl:operation name="DispPlanificacionOp">
			<wsdl:input message="tns:dispPlanificacionRequest" />
			<wsdl:output message="tns:dispPlanificacionResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="DispPlanificacionPortBinding" type="tns:WsDispPlanificacion">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="DispPlanificacionOp">
			<soap:operation
				soapAction="http://soap.sctinst.redsys.es/WS_DISP_PLANIFICACION/DispPlanificacionOp" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="WS_DISP_PLANIFICACION_service">
		<wsdl:port binding="tns:DispPlanificacionPortBinding" name="WsDispPlanificacionPort">
			<soap:address location="https://sctinst-i.redsys.es/sbasico-entadm/WS_DISP_PLANIFICACION" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>